// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------

package endpoints

import (
	"net/http"

	chi "github.com/go-chi/chi/v5"
	"github.com/swaggest/rest/nethttp"
	"github.com/swaggest/rest/web"
)

func AddEndpoints(s *web.Service, jwtAuth func(http.Handler) http.Handler) {
	s.Route("/v1", func(r chi.Router) {
		r.Group(func(r chi.Router) {
			//r.Use(adminAuth, nethttp.HTTPBasicSecurityMiddleware(s.OpenAPICollector, "User", "User access"))
			r.Use(jwtAuth, nethttp.HTTPBearerSecurityMiddleware(s.OpenAPICollector, "Bearer", "", ""))
			//	r.Use(rateLimitByAppId(50))
			//r.Method(http.MethodPost, "/", nethttp.NewHandler(ExchangeCreateRoomsPost()))
			r.Method(http.MethodPost, "/health/ping", nethttp.NewHandler(HealthPingPost()))
			r.Method(http.MethodPost, "/health/coreversion", nethttp.NewHandler(HealthCoreversionPost()))
			r.Method(http.MethodPost, "/discover/discover", nethttp.NewHandler(DiscoverDiscoverPost()))
			r.Method(http.MethodPost, "/connect/connectionstrings", nethttp.NewHandler(ConnectConnectionstringsPost()))
			r.Method(http.MethodPost, "/connect/forward", nethttp.NewHandler(ConnectForwardPost()))
			r.Method(http.MethodPost, "/backup/all", nethttp.NewHandler(BackupAllPost()))
			r.Method(http.MethodPost, "/restore/list", nethttp.NewHandler(RestoreListPost()))
			r.Method(http.MethodPost, "/restore/download", nethttp.NewHandler(RestoreDownloadPost()))
			r.Method(http.MethodPost, "/restore/unarchive", nethttp.NewHandler(RestoreUnarchivePost()))
			r.Method(http.MethodPost, "/restore/listtar", nethttp.NewHandler(RestoreListtarPost()))

		})
	})

}
