// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Get connection strings
---
*/
package endpoints

import (
	"context"
	"encoding/json"
	"os"
	"path"

	"github.com/swaggest/usecase"

	"github.com/365admin/magicbox-mongodb/execution"
	"github.com/365admin/magicbox-mongodb/schemas"
	"github.com/365admin/magicbox-mongodb/utils"
)

func ConnectConnectionstringsPost() usecase.Interactor {
	type Request struct {
		Databasename string `query:"databasename" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *schemas.Connectionstrings) error {

		_, err := execution.ExecutePowerShell("john", "*", "magicbox-mongodb", "07-connect", "10 get-connectionstring.ps1", "", "-databasename", input.Databasename)
		if err != nil {
			return err
		}

		resultingFile := path.Join(utils.WorkDir("magicbox-mongodb"), "connectionstrings.json")
		data, err := os.ReadFile(resultingFile)
		if err != nil {
			return err
		}
		resultObject := schemas.Connectionstrings{}
		err = json.Unmarshal(data, &resultObject)
		*output = resultObject
		return err

	})
	u.SetTitle("Get connection strings")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Connect")
	return u
}
