// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Forward To Database
---
*/
package endpoints

import (
	"context"

	"github.com/swaggest/usecase"

	"github.com/365admin/magicbox-mongodb/execution"
)

func ConnectForwardPost() usecase.Interactor {
	type Request struct {
		Databasename string `query:"databasename" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "magicbox-mongodb", "07-connect", "20-forward.ps1", "", "-databasename", input.Databasename)
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Forward To Database")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Connect")
	return u
}
