// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Backup All
---
*/
package endpoints

import (
	"context"

	"github.com/swaggest/usecase"

	"github.com/365admin/magicbox-mongodb/execution"
)

func MagicBackupPost() usecase.Interactor {
	type Request struct {
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "magicbox-mongodb", "00-magic", "10-discover-and-backup.ps1", "")
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Backup All")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Magic Buttons")
	return u
}
