apiVersion: apps/v1
kind: Deployment
metadata:
  name: datahostwithsidecar
spec:
  selector:
    matchLabels:
      app: datahostwithsidecar
  replicas: 1
  template:
    metadata:
      labels:
        app: datahostwithsidecar
    spec:
      containers:
        - name: datahost
          image: busybox
          command: ["sh","-c","while true;  sleep 30; done"]
          volumeMounts:
            - name: backup
              mountPath: /data/backup
        - name: sidecar
          image: busybox
          command: ["sh","-c","while true; sleep 30; done"]
          volumeMounts:
            - name: backup
              mountPath: /data/backup
      volumes:
        - name: backup
          emptyDir: {}
                                    


                                    

